// Code generated by "astra generate:glue" on 2026-04-10T11:43:06+05:30. DO NOT EDIT.
package repositories

import (
	"github.com/shauryagautam/Astra/pkg/database"
	"github.com/shauryagautam/Astra/app/models"
)

// RegisterAllModels enrolls all discovered model metadata into the ORM registry.
// This eliminates runtime reflection overhead for metadata extraction.
func RegisterAllModels() {
	database.RegisterModel[models.Todo](database.ModelMeta{
		TableName: "todos",
		Columns: []database.ColumnMeta{
			{
				FieldName:  "ID",
				ColumnName: "id",
				FieldIndex: []int{ 0 },
				IsPK:       true,
				IsAuto:     true,
				IsSoftDel:  false,
				IsGuarded:  false,
				IsNullZero: false,
			},
			{
				FieldName:  "Title",
				ColumnName: "title",
				FieldIndex: []int{ 1 },
				IsPK:       false,
				IsAuto:     false,
				IsSoftDel:  false,
				IsGuarded:  false,
				IsNullZero: false,
			},
			{
				FieldName:  "Completed",
				ColumnName: "completed",
				FieldIndex: []int{ 2 },
				IsPK:       false,
				IsAuto:     false,
				IsSoftDel:  false,
				IsGuarded:  false,
				IsNullZero: false,
			},
			{
				FieldName:  "CreatedAt",
				ColumnName: "created_at",
				FieldIndex: []int{ 3 },
				IsPK:       false,
				IsAuto:     false,
				IsSoftDel:  false,
				IsGuarded:  false,
				IsNullZero: false,
			},
			{
				FieldName:  "UpdatedAt",
				ColumnName: "updated_at",
				FieldIndex: []int{ 4 },
				IsPK:       false,
				IsAuto:     false,
				IsSoftDel:  false,
				IsGuarded:  false,
				IsNullZero: false,
			},
		},
	})
}
