// Code generated by "astra generate:glue" on 2026-04-10. DO NOT EDIT.
package repositories

import (
	"context"
	"fmt"

	"github.com/shauryagautam/Astra/pkg/database"
	"github.com/shauryagautam/Astra/app/models"
)

// TodoRepository provides type-safe CRUD operations for Todo.
type TodoRepository struct {
	*database.BaseRepository[models.Todo]
}

// NewTodoRepository creates a new TodoRepository backed by db.
func NewTodoRepository(db *database.DB) *TodoRepository {
	return &TodoRepository{
		BaseRepository: database.NewBaseRepository[models.Todo](db),
	}
}

// FindByID returns a single Todo by primary key.
// Overridden to provide zero-reflection manual scanning for maximum performance.
func (r *TodoRepository) FindByID(ctx context.Context, id any) (*models.Todo, error) {
	var m models.Todo
	query := "SELECT * FROM todos WHERE id = ? LIMIT 1"
	
	row := r.DB.Pool().QueryRowContext(ctx, query, id)
	err := row.Scan(
		&m.ID,
		&m.Title,
		&m.Completed,
		&m.CreatedAt,
		&m.UpdatedAt,
		
	)
	if err != nil {
		return nil, err
	}
	return &m, nil
}
