// Code generated by "astra generate:glue" on 2026-04-10. DO NOT EDIT.
package handlers

import (
	"net/http"
	"strconv"

	astrahttp "github.com/shauryagautam/Astra/http"
	"github.com/shauryagautam/Astra/app/models"
	"github.com/shauryagautam/Astra/app/repositories"
)

// TodoHandler handles HTTP CRUD requests for Todo.
type TodoHandler struct {
	repo *repositories.TodoRepository
}

// NewTodoHandler creates a new TodoHandler.
func NewTodoHandler(repo *repositories.TodoRepository) *TodoHandler {
	return &TodoHandler{repo: repo}
}

// Index handles GET /todos
func (h *TodoHandler) Index(c *astrahttp.Context) error {
	page, _ := strconv.Atoi(c.QueryDefault("page", "1"))
	perPage, _ := strconv.Atoi(c.QueryDefault("per_page", "25"))

	records, err := h.repo.FindAll(c.Ctx(), page, perPage)
	if err != nil {
		return err
	}
	total, err := h.repo.Count(c.Ctx())
	if err != nil {
		return err
	}

	return c.JSON(map[string]any{
		"data":     records,
		"total":    total,
		"page":     page,
		"per_page": perPage,
	}, http.StatusOK)
}

// Show handles GET /todos/{id}
func (h *TodoHandler) Show(c *astrahttp.Context) error {
	id := c.Param("id")
	record, err := h.repo.FindByID(c.Ctx(), id)
	if err != nil {
		return err
	}
	return c.JSON(record, http.StatusOK)
}

// Store handles POST /todos
func (h *TodoHandler) Store(c *astrahttp.Context) error {
	var input models.Todo
	if err := c.Bind(&input); err != nil {
		return err
	}
	record, err := h.repo.Create(c.Ctx(), &input)
	if err != nil {
		return err
	}
	return c.JSON(record, http.StatusCreated)
}

// Update handles PUT /todos/{id}
func (h *TodoHandler) Update(c *astrahttp.Context) error {
	id := c.Param("id")
	existing, err := h.repo.FindByID(c.Ctx(), id)
	if err != nil {
		return err
	}
	if err := c.Bind(existing); err != nil {
		return err
	}
	if err := h.repo.Update(c.Ctx(), existing); err != nil {
		return err
	}
	return c.JSON(existing, http.StatusOK)
}

// Destroy handles DELETE /todos/{id}
func (h *TodoHandler) Destroy(c *astrahttp.Context) error {
	id := c.Param("id")
	if err := h.repo.Delete(c.Ctx(), id); err != nil {
		return err
	}
	return c.NoContent()
}
