package codegen

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

func parseGoTypeToTS(goType string) string {
	// Handle pointer types
	if strings.HasPrefix(goType, "*") {
		return parseGoTypeToTS(goType[1:]) + " | null"
	}
	// Handle slice types
	if strings.HasPrefix(goType, "[]") {
		return parseGoTypeToTS(goType[2:]) + "[]"
	}
	// Handle map types
	if strings.HasPrefix(goType, "map[string]") {
		return "Record<string, " + parseGoTypeToTS(goType[11:]) + ">"
	}
	if strings.HasPrefix(goType, "map[") {
		closeBracket := strings.Index(goType, "]")
		if closeBracket > 4 {
			keyType := goType[4:closeBracket]
			valType := goType[closeBracket+1:]
			return fmt.Sprintf("Record<%s, %s>", parseGoTypeToTS(keyType), parseGoTypeToTS(valType))
		}
	}

	switch goType {
	case "string":
		return "string"
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"float32", "float64":
		return "number"
	case "bool":
		return "boolean"
	case "time.Time", "uuid.UUID":
		return "string" // ISO8601 or UUID string
	case "json.RawMessage":
		return "Record<string, unknown>"
	case "any", "interface{}":
		return "any"
	default:
		// If it starts with an uppercase letter, it's likely a custom struct type
		if len(goType) > 0 {
			firstChar := goType[0]
			if firstChar >= 'A' && firstChar <= 'Z' {
				return goType
			}
		}
		return "unknown"
	}
}

func toPascalCase(s string) string {
	parts := strings.Split(s, "_")
	for i := range parts {
		if len(parts[i]) > 0 {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}

// Generator handles generating TypeScript files.
type Generator struct {
	OutputDir string
}

// NewGenerator creates a new generator.
func NewGenerator(outputDir string) *Generator {
	return &Generator{OutputDir: outputDir}
}

// Generate creates the client files.
func (g *Generator) Generate(meta *Metadata) error {
	if err := os.MkdirAll(g.OutputDir, 0755); err != nil {
		return err
	}

	if err := g.generateTypes(meta); err != nil {
		return err
	}
	if err := g.generateClient(meta); err != nil {
		return err
	}
	if err := g.generateWSClient(); err != nil {
		return err
	}
	if err := g.generateGraphQLClient(); err != nil {
		return err
	}
	if err := g.generateRNClient(meta); err != nil {
		return err
	}
	if err := g.generateHooks(meta); err != nil {
		return err
	}
	if err := g.generateIndex(); err != nil {
		return err
	}

	return nil
}

func (g *Generator) generateTypes(meta *Metadata) error {
	var sb strings.Builder
	sb.WriteString("// Auto-generated by Astra. DO NOT EDIT.\n\n")

	for _, s := range meta.Structs {
		sb.WriteString(fmt.Sprintf("export interface %s {\n", s.Name))
		for _, f := range s.Fields {
			tsType := parseGoTypeToTS(f.Type)

			jsonName := f.Name
			if strings.Contains(f.Tag, "json:") {
				parts := strings.Split(f.Tag, "\"")
				if len(parts) >= 3 {
					jsonName = strings.Split(parts[1], ",")[0]
				}
			}
			if jsonName == "-" {
				continue
			}

			sb.WriteString(fmt.Sprintf("  %s: %s;\n", jsonName, tsType))
		}
		sb.WriteString("}\n\n")
	}

	return os.WriteFile(filepath.Join(g.OutputDir, "types.ts"), []byte(sb.String()), 0644)
}

func (g *Generator) generateClient(meta *Metadata) error {
	tmpl := `// Auto-generated by Astra. DO NOT EDIT.

export class AstraClient {
  private baseUrl: string;
  private token: string | null = null;

  constructor(baseUrl: string) {
    this.baseUrl = baseUrl;
  }

  setToken(token: string) {
    this.token = token;
  }

  private async request(method: string, path: string, data?: any): Promise<any> {
    const headers: Record<string, string> = {
      'Content-Type': 'application/json',
    };
    if (this.token) {
      headers['Authorization'] = 'Bearer ' + this.token;
    }

    const url = this.baseUrl + path;
    const options: RequestInit = { method, headers };

    if (data && method !== 'GET' && method !== 'HEAD') {
      options.body = JSON.stringify(data);
    }

    let response = await fetch(url, options);

    // Auto-refresh on 401
    if (response.status === 401 && !path.includes('/auth/refresh') && !path.includes('/auth/login')) {
      const refreshOk = await this.refreshToken();
      if (refreshOk) {
        // Retry with new token
        if (this.token) {
          headers['Authorization'] = 'Bearer ' + this.token;
        }
        response = await fetch(url, options);
      }
    }

    if (!response.ok) {
      throw new Error('API Error: ' + response.statusText);
    }
    
    // Attempt to return json, fallback to text
    const text = await response.text();
    try {
      return JSON.parse(text);
    } catch {
      return text;
    }
  }

  private async refreshToken(): Promise<boolean> {
    try {
      const resp = await fetch(this.baseUrl + '/auth/refresh', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
      });
      if (resp.ok) {
        const data = await resp.json();
        if (data.token) {
          this.setToken(data.token);
          return true;
        }
      }
    } catch (err) {
      console.error('[Astra Client] Token refresh failed', err);
    }
    return false;
  }

{{range .Routes}}
  async {{.Name}}(data?: {{.Input}}): Promise<{{.Output}}> {
    return this.request('{{.Method}}', '{{.Path}}', data);
  }
{{end}}
}
`
	t, err := template.New("client").Parse(tmpl)
	if err != nil {
		return err
	}

	var buf bytes.Buffer
	if err := t.Execute(&buf, meta); err != nil {
		return err
	}

	return os.WriteFile(filepath.Join(g.OutputDir, "client.ts"), buf.Bytes(), 0644)
}

func (g *Generator) generateWSClient() error {
	content := `// Auto-generated by Astra. DO NOT EDIT.

export class AstraWSClient {
  private socket: WebSocket | null = null;
  private handlers: Map<string, ((data: any) => void)[]> = new Map();
  private reconnectAttempts = 0;
  private maxReconnectAttempts = 5;

  connect(url: string, token?: string): void {
    const wsUrl = token ? ` + "`" + `${url}?token=${token}` + "`" + ` : url;
    this.socket = new WebSocket(wsUrl);

    this.socket.onopen = () => {
      this.reconnectAttempts = 0;
      console.log('[Astra WS] Connected');
    };

    this.socket.onmessage = (event) => {
      const msg = JSON.parse(event.data) as { event: string; data: any };
      const handlers = this.handlers.get(msg.event) ?? [];
      handlers.forEach(h => h(msg.data));
    };

    this.socket.onclose = () => {
      this.scheduleReconnect(url, token);
    };
  }

  on<T>(event: string, handler: (data: T) => void): () => void {
    const handlers = this.handlers.get(event) ?? [];
    this.handlers.set(event, [...handlers, handler as (data: any) => void]);
    return () => this.off(event, handler);
  }

  off(event: string, handler: (data: any) => void): void {
    const handlers = this.handlers.get(event) ?? [];
    this.handlers.set(event, handlers.filter(h => h !== handler));
  }

  emit(event: string, data: any): void {
    this.socket?.send(JSON.stringify({ event, data }));
  }

  join(room: string): void {
    this.emit('__join', { room });
  }

  leave(room: string): void {
    this.emit('__leave', { room });
  }

  private scheduleReconnect(url: string, token?: string): void {
    if (this.reconnectAttempts >= this.maxReconnectAttempts) return;
    const delay = Math.min(1000 * 2 ** this.reconnectAttempts, 30000);
    this.reconnectAttempts++;
    setTimeout(() => this.connect(url, token), delay);
  }

  disconnect(): void {
    this.socket?.close();
    this.socket = null;
  }
}
`
	return os.WriteFile(filepath.Join(g.OutputDir, "ws.ts"), []byte(content), 0644)
}

func (g *Generator) generateHooks(meta *Metadata) error {
	var sb strings.Builder
	sb.WriteString(`// Auto-generated by Astra. DO NOT EDIT.
import { useQuery, useMutation } from '@tanstack/react-query';
import { useRef, useEffect } from 'react';
import { AstraClient } from './client';
import { AstraWSClient } from './ws';

export const api = new AstraClient(''); // Replace with context injection

export function useAuthToken() {
  // Replace with actual implementation (e.g. from context or localStorage)
  return { data: api.getToken?.() ?? null };
}

export function useAstraQuery<TData = any>(key: any[], fetcher: () => Promise<TData>) {
  return useQuery({ queryKey: key, queryFn: fetcher });
}

export function useAstraMutation<TData = any, TVariables = any>(mutationFn: (variables: TVariables) => Promise<TData>) {
  return useMutation({ mutationFn });
}
`)

	hasWS := false
	for _, r := range meta.Routes {
		if r.Method == "WS" {
			hasWS = true
			continue
		}
		namePascal := toPascalCase(r.Name)
		out := parseGoTypeToTS(r.Output)
		in := parseGoTypeToTS(r.Input)

		if r.Method == "GET" || r.Method == "HEAD" {
			sb.WriteString(fmt.Sprintf("\nexport function use%s() {\n", namePascal))
			sb.WriteString(fmt.Sprintf("  return useAstraQuery<%s>(['%s'], () => api.%s());\n", out, r.Name, r.Name))
			sb.WriteString("}\n")
		} else {
			if in == "any" {
				in = "void"
			}
			sb.WriteString(fmt.Sprintf("\nexport function use%s() {\n", namePascal))
			sb.WriteString(fmt.Sprintf("  return useAstraMutation<%s, %s>((data) => api.%s(data));\n", out, in, r.Name))
			sb.WriteString("}\n")
		}
	}

	if hasWS {
		sb.WriteString(`
export function useAstraWS(room?: string) {
  const ws = useRef(new AstraWSClient());
  const { data: token } = useAuthToken();

  useEffect(() => {
    const client = ws.current;
    const wsUrl = process.env.NEXT_PUBLIC_WS_URL || 'ws://localhost:8080/ws';
    client.connect(wsUrl, token || undefined);
    if (room) client.join(room);
    return () => {
      if (room) client.leave(room);
      client.disconnect();
    };
  }, [room, token]);

  return ws.current;
}
`)
	}

	return os.WriteFile(filepath.Join(g.OutputDir, "hooks.ts"), []byte(sb.String()), 0644)
}

func (g *Generator) generateRNClient(meta *Metadata) error {
	tmpl := `// Auto-generated by Astra. DO NOT EDIT.
import * as SecureStore from 'expo-secure-store';

export class AstraMobileClient {
  private baseUrl: string;

  constructor(baseUrl: string) {
    this.baseUrl = baseUrl;
  }

  async setToken(token: string) {
    await SecureStore.setItemAsync('astra_token', token);
  }

  async getToken() {
    return await SecureStore.getItemAsync('astra_token');
  }

  private async request(method: string, path: string, data?: any) {
    const token = await this.getToken();
    const headers: Record<string, string> = {
      'Content-Type': 'application/json',
    };
    if (token) {
      headers['Authorization'] = 'Bearer ' + token;
    }

    const url = this.baseUrl + path;
    const options: any = { method, headers };

    if (data && method !== 'GET' && method !== 'HEAD') {
      options.body = JSON.stringify(data);
    }

    const response = await fetch(url, options);
    if (!response.ok) {
      throw new Error('API Error: ' + response.statusText);
    }
    
    return response.json();
  }

{{range .Routes}}
  async {{.Name}}(data?: {{.Input}}): Promise<{{.Output}}> {
    return this.request('{{.Method}}', '{{.Path}}', data);
  }
{{end}}
}
`
	t, err := template.New("mobile").Parse(tmpl)
	if err != nil {
		return err
	}

	var buf bytes.Buffer
	if err := t.Execute(&buf, meta); err != nil {
		return err
	}

	return os.WriteFile(filepath.Join(g.OutputDir, "mobile.ts"), buf.Bytes(), 0644)
}

func (g *Generator) generateGraphQLClient() error {
	// Look for schema files
	schemaDir := "graphql"
	if _, err := os.Stat(schemaDir); os.IsNotExist(err) {
		return nil // No graphql directory, skip
	}

	var schemaSb strings.Builder
	err := filepath.Walk(schemaDir, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() || !strings.HasSuffix(path, ".graphql") {
			return nil
		}
		content, err := os.ReadFile(path)
		if err == nil {
			schemaSb.Write(content)
			schemaSb.WriteString("\n")
		}
		return nil
	})
	if err != nil {
		return err
	}

	if schemaSb.Len() == 0 {
		return nil
	}

	// Basic GraphQL client generation
	content := `// Auto-generated by Astra. DO NOT EDIT.
import { GraphQLClient } from 'graphql-request';
import { useQuery, useMutation } from '@tanstack/react-query';

const endpoint = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8080';
const gqlClient = new GraphQLClient(endpoint + '/graphql', {
  headers: () => {
    const token = typeof window !== 'undefined' ? localStorage.getItem('astra_access_token') : null;
    return token ? { Authorization: ` + "`" + `Bearer ${token}` + "`" + ` } : {};
  }
});

export const gql = gqlClient;

// Add high-level helpers here...
`
	return os.WriteFile(filepath.Join(g.OutputDir, "graphql.ts"), []byte(content), 0644)
}

func (g *Generator) generateIndex() error {
	content := `export * from './types';
export * from './client';
export * from './ws';
export * from './graphql';
export * from './mobile';
export * from './hooks';
`
	return os.WriteFile(filepath.Join(g.OutputDir, "index.ts"), []byte(content), 0644)
}
