// Auto-generated by Astra. DO NOT EDIT.

export class AstraClient {
  private baseUrl: string;
  private token: string | null = null;

  constructor(baseUrl: string) {
    this.baseUrl = baseUrl;
  }

  setToken(token: string) {
    this.token = token;
  }

  private async request(method: string, path: string, data?: any) {
    const headers: Record<string, string> = {
      'Content-Type': 'application/json',
    };
    if (this.token) {
      headers['Authorization'] = 'Bearer ' + this.token;
    }

    const url = this.baseUrl + path;
    const options: RequestInit = { method, headers };

    if (data && method !== 'GET' && method !== 'HEAD') {
      options.body = JSON.stringify(data);
    }

    const response = await fetch(url, options);
    if (!response.ok) {
      throw new Error('API Error: ' + response.statusText);
    }
    
    // Attempt to return json, fallback to text
    const text = await response.text();
    try {
      return JSON.parse(text);
    } catch {
      return text;
    }
  }


}
