// Auto-generated by Astra. DO NOT EDIT.
import { useQuery, useMutation } from '@tanstack/react-query';
import { AstraClient } from './client';

export const api = new AstraClient(''); // Replace with context injection

export function useAstraQuery<TData = any>(key: any[], fetcher: () => Promise<TData>) {
  return useQuery({ queryKey: key, queryFn: fetcher });
}

export function useAstraMutation<TData = any, TVariables = any>(mutationFn: (variables: TVariables) => Promise<TData>) {
  return useMutation({ mutationFn });
}
